name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install CUSTOMIZED lua
      uses : actions/checkout@v3
      with :
        repository: Tekenlight/lua
        path: .
    - name: Build customized lua
      run: make linux
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: make test
      run: make test
   
